# Generated by Django 5.2.5 on 2025-09-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPermissionAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'External Permission',
                'verbose_name_plural': 'External Permissions',
            },
        ),
    ]
