services:
  pyauthservice:
    image: ${FULL_IMAGE}:${IMAGE_TAG}
    user: "1000:1000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyauthservice
    restart: unless-stopped
    ports:
      - "${PORT:-8000:8000}"
    volumes:
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    entrypoint: /app/entrypoint.sh
    command: gunicorn pyauthservice.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120 --access-logfile - --error-logfile -